name: CI Build

on:
  workflow_dispatch:
    branches: [main]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  test-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@juliusagency'
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_FROM_REGISTRY }}
      - name: Run build
        run: npm run build --if-present
      - name: Run tests
        run: npm test
