name: Publish To GitHub

on:
  workflow_dispatch:
    branches: [main]
    tags:
      - "v*-node-starter-with-auth-ses-sql"
jobs:
  publish-node-starter-with-auth-ses-sql-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/juliusagency/node-starter-with-auth-ses-sql 
      #     flavor: latest=true
      #     tags: |
      #       type=ref,event=branch
      #       type=ref,event=pr
      #       type=semver,pattern={{version}}
      
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker build . --tag ghcr.io/juliusagency/node-starter-with-auth-ses-sql:latest
          docker run ghcr.io/juliusagency/node-starter-with-auth-ses-sql:latest
          docker push ghcr.io/juliusagency/node-starter-with-auth-ses-sql:latest

        # uses: docker/build-push-action@v3
        # with:
        #   context: .
        #   file: ./Dockerfile
        #   build-args: |
        #     "READ_FROM_REGISTRY=${{ secrets.READ_FROM_REGISTRY }}"
        #   push: ${{ github.ref_type == 'tag' }}
        #   tags: ${{ steps.meta.outputs.tags }}
        #   labels: ${{ steps.meta.outputs.labels }}