name: Publish To GitHub

on:
  workflow_dispatch:
    branches: [main]
jobs:
  publish-auth_ses-sql-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          scope: '@juliusagency'
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_FROM_REGISTRY }}
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}